<a href="https://colab.research.google.com/github/LucjanSakowicz/data-science-bootcamp/blob/main/09_exercises/051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.22.4'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [3]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate((A, B))

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [4]:
np.concatenate((A, B), axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [5]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

np.append(data, target, axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [7]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
np.column_stack((feature1, feature2, feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [10]:
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[5 5 5 1]
 [1 1 3 1]
 [6 6 5 6]
 [4 1 6 4]
 [3 4 0 4]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [11]:
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A)

21

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [12]:
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A)

28

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [16]:
A = np.random.randn(10, 4)
print(A)
np.set_printoptions(precision=4)
print(A)

[[-0.48536355  0.08187414  2.31465857 -1.86726519]
 [ 0.68626019 -1.61271587 -0.47193187  1.0889506 ]
 [ 0.06428002 -1.07774478 -0.71530371  0.67959775]
 [-0.73036663  0.21645859  0.04557184 -0.65160035]
 [ 2.14394409  0.63391902 -2.02514259  0.18645431]
 [-0.66178646  0.85243333 -0.79252074 -0.11473644]
 [ 0.50498728  0.86575519 -1.20029641 -0.33450124]
 [-0.47494531 -0.65332923  1.76545424  0.40498171]
 [-1.26088395  0.91786195  2.1221562   1.03246526]
 [-1.51936997 -0.48423407  1.26691115 -0.70766947]]
[[-0.4854  0.0819  2.3147 -1.8673]
 [ 0.6863 -1.6127 -0.4719  1.089 ]
 [ 0.0643 -1.0777 -0.7153  0.6796]
 [-0.7304  0.2165  0.0456 -0.6516]
 [ 2.1439  0.6339 -2.0251  0.1865]
 [-0.6618  0.8524 -0.7925 -0.1147]
 [ 0.505   0.8658 -1.2003 -0.3345]
 [-0.4749 -0.6533  1.7655  0.405 ]
 [-1.2609  0.9179  2.1222  1.0325]
 [-1.5194 -0.4842  1.2669 -0.7077]]


### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [20]:
A = np.array([1.2e-6, 1.7e-7])
print(A)
np.set_printoptions(precision=8, suppress=True)
print(A)

[0. 0.]
[0.0000012  0.00000017]


### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [23]:
A = np.random.randn(8, 4)
print(A)
print(np.delete(A, 2, 1))

[[-0.81822068  2.09238728 -1.00601738 -1.21418861]
 [ 1.15811087  0.79166269  0.62411982  0.62834551]
 [-0.01224677 -0.89725437  0.07580456 -0.67716171]
 [ 0.97511973 -0.14705738 -0.8254972  -0.32138584]
 [ 0.41293145 -0.56372455 -0.8222204   0.24368721]
 [ 0.24496657 -0.50694318 -0.47103831  0.23204994]
 [-1.44808434 -1.40746377 -0.71844422 -0.21344715]
 [ 0.31090757  1.47535622  0.85765962 -0.15993853]]
[[-0.81822068  2.09238728 -1.21418861]
 [ 1.15811087  0.79166269  0.62834551]
 [-0.01224677 -0.89725437 -0.67716171]
 [ 0.97511973 -0.14705738 -0.32138584]
 [ 0.41293145 -0.56372455  0.24368721]
 [ 0.24496657 -0.50694318  0.23204994]
 [-1.44808434 -1.40746377 -0.21344715]
 [ 0.31090757  1.47535622 -0.15993853]]



### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [25]:
v = np.array([3, 4, -2])
np.sqrt(sum([i*i for i in v]))

#lub

np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [26]:
A = np.random.randint(10, size=(100, 30))
A

array([[6, 2, 1, ..., 8, 1, 8],
       [0, 0, 4, ..., 4, 3, 2],
       [5, 1, 2, ..., 4, 6, 5],
       ...,
       [7, 7, 3, ..., 4, 5, 5],
       [5, 1, 9, ..., 3, 2, 1],
       [0, 4, 1, ..., 1, 6, 7]])

In [28]:
np.set_printoptions(edgeitems=10)

In [29]:
A

array([[6, 2, 1, 9, 3, 7, 8, 6, 0, 2, ..., 5, 4, 4, 3, 2, 2, 3, 8, 1, 8],
       [0, 0, 4, 5, 5, 2, 6, 8, 9, 7, ..., 4, 8, 3, 5, 0, 8, 0, 4, 3, 2],
       [5, 1, 2, 4, 8, 1, 9, 7, 1, 4, ..., 5, 0, 0, 1, 8, 2, 0, 4, 6, 5],
       [0, 4, 4, 5, 2, 4, 6, 4, 4, 4, ..., 0, 7, 1, 7, 6, 9, 9, 1, 5, 5],
       [2, 1, 0, 5, 4, 8, 0, 6, 4, 4, ..., 1, 3, 8, 5, 0, 7, 6, 9, 2, 0],
       [4, 3, 9, 7, 0, 9, 0, 3, 7, 4, ..., 3, 7, 3, 7, 8, 2, 2, 1, 9, 2],
       [2, 4, 4, 1, 9, 5, 4, 5, 0, 4, ..., 7, 0, 9, 3, 0, 7, 0, 2, 3, 7],
       [5, 9, 6, 7, 1, 9, 7, 2, 6, 2, ..., 6, 8, 0, 6, 5, 9, 8, 0, 3, 8],
       [3, 9, 2, 8, 1, 3, 5, 1, 7, 7, ..., 5, 4, 8, 0, 4, 5, 4, 5, 5, 6],
       [3, 7, 6, 8, 6, 2, 2, 7, 4, 3, ..., 2, 8, 1, 7, 9, 2, 4, 5, 9, 5],
       ...,
       [5, 3, 3, 1, 1, 3, 4, 7, 5, 3, ..., 8, 0, 9, 9, 1, 5, 5, 0, 6, 7],
       [1, 7, 8, 5, 4, 8, 8, 0, 2, 8, ..., 4, 0, 9, 6, 9, 0, 8, 7, 6, 9],
       [6, 4, 4, 4, 0, 7, 0, 3, 8, 8, ..., 8, 2, 1, 2, 8, 6, 8, 1, 4, 3],
       [1, 8, 8, 5, 5, 7, 