<a href="https://colab.research.google.com/github/LucjanSakowicz/data-science-bootcamp/blob/main/09_exercises/071_080_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 71](#1)
* [Ćwiczenie 72](#2)
* [Ćwiczenie 73](#3)
* [Ćwiczenie 74](#4)
* [Ćwiczenie 75](#5)
* [Ćwiczenie 76](#6)
* [Ćwiczenie 77](#7)
* [Ćwiczenie 78](#8)
* [Ćwiczenie 79](#9)
* [Ćwiczenie 80](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.22.4'

### <a name='1'></a> Ćwiczenie 71
Podana jest poniższa tablica $A$:

```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
Od drugiego wiersza tablicy $A$ przestaw losowo wiersze w tablicy.

__Wskazówka:__ Użyj funkcji _np.random.shuffle()_.


In [12]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
np.random.shuffle(A[1:])
print(A)

[['id' 'price']
 ['002' '4.99']
 ['004' '2.49']
 ['005' '1.49']
 ['003' '7.99']
 ['001' '14.99']]


### <a name='2'></a> Ćwiczenie 72
Podana jest poniższa tablica $A$:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Zwróć tablicę indeksów, które posortują tablicę $A$ rosnąco.

__Oczekiwny wynik:__


```
array([5, 2, 1, 0, 4, 3])
```
__Wskazówka:__ Użyj funkcji _np.argsort()_.



In [13]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
np.argsort(A)

array([5, 2, 1, 0, 4, 3])

### <a name='3'></a> Ćwiczenie 73
Podana jest poniższa tablica $A$:

```
A = np.random.randn(10, 8)
```

Zaokrąglij wartości tej tablicy do trzeciego miejsca po przecinku.

__Wskazówka:__ Użyj funkcji _np.round()_.

In [15]:
A = np.random.randn(10, 8)
np.round(A, 3)

array([[-0.258,  0.461, -1.349, -1.019,  0.127, -1.249,  1.945, -0.153],
       [-0.907, -0.817, -0.483, -0.57 , -2.092,  1.264, -0.015, -0.027],
       [ 0.818, -1.055, -0.758,  0.457, -0.064,  0.345, -0.08 , -0.241],
       [ 1.434,  1.066, -2.499,  1.48 ,  2.159,  1.232, -0.214, -0.689],
       [ 0.728, -0.619,  0.356, -0.022,  1.218, -0.389, -0.443,  0.378],
       [ 1.934,  0.081, -0.416,  0.858,  0.718, -0.951, -0.536,  1.097],
       [ 0.428, -2.47 ,  0.482,  0.926, -0.838,  0.677,  1.872,  0.396],
       [-0.626, -0.522,  0.013,  0.378,  0.063,  0.502, -0.147,  0.181],
       [ 0.965, -1.065,  0.109,  0.106,  0.921, -0.227,  0.653,  1.103],
       [-1.85 ,  1.169, -0.985, -1.094, -2.879, -0.803, -0.005, -0.383]])

### <a name='4'></a> Ćwiczenie 74
Wyznacz pierwiastki wielomianu:
* $W(x) = 4x^2 + 5x + 1$


__Wskazówka:__ Użyj funkcji _np.roots()_ oraz _np.polyval()_.

In [47]:
W = np.array([4, 5, 1])
np.roots((4, 5, 1))
#lub
np.roots(W)

array([-1.  , -0.25])

Dokonaj sprawdzenia.

In [48]:
4*np.power(-1, 2)+5*-1+1

# lub

np.polyval(W, -1)

0

In [49]:
4*np.power(-0.25, 2)+5*-0.25+1

# lub

np.polyval(W, -0.25)

0.0

### <a name='5'></a> Ćwiczenie 75
Wyznacz pierwiastki wielomianów:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Wskazówka:__ Użyj funkcji _np.roots()_.

In [24]:
print(np.roots((2, 4, -5, 1)))
print(np.roots((2, 0, -5, 1)))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


### <a name='6'></a> Ćwiczenie 76
Podane są wielomiany:

* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [50]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Wykonaj działania:
* $W(x) + Q(x)$

In [51]:
np.polyadd(W, Q)

array([2, 8, 0, 2])

* $W(x) - Q(x)$


In [52]:
np.polysub(W, Q)

array([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [53]:
np.polymul(W, Q)

array([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [54]:
np.polyadd(W, 2*Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Ćwiczenie 77
Podana jest poniższa tablica:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```

Użyj funkcji znaku (_sign function_) dla tablicy $A$. Dla przypomnienia funkcja działa nastpująco: dla wartości ujemnych zwraca -1, dla zera wartość zero, dla wartości dodatnich 1.

__Oczekiwany wynik:__


```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Wskazówka:__ Użyj funkcji _np.sign()_.


In [39]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Ćwiczenie 78
Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:


```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```



In [41]:
np.arange(start='2021-01-01', stop='2021-02-01', dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')


### <a name='9'></a> Ćwiczenie 79

Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:



```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```



In [42]:
np.arange(start='2021-01', stop='2022-01', dtype='datetime64[M]')

array(['2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06',
       '2021-07', '2021-08', '2021-09', '2021-10', '2021-11', '2021-12'],
      dtype='datetime64[M]')

### <a name='10'></a> Ćwiczenie 80

Wykorzystując funkcję _np.datetime64()_ wygeneruj dzisiejszą datę (datę w chwili robienia ćwiczenia).

In [45]:
np.datetime64('today')

numpy.datetime64('2023-05-16')