<a href="https://colab.research.google.com/github/LucjanSakowicz/data-science-bootcamp/blob/main/09_exercises/221_230_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Science Bootcamp

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 221](#1)
* [Ćwiczenie 222](#2)
* [Ćwiczenie 223](#3)
* [Ćwiczenie 224](#4)
* [Ćwiczenie 225](#5)
* [Ćwiczenie 226](#6)
* [Ćwiczenie 227](#7)
* [Ćwiczenie 228](#8)
* [Ćwiczenie 229](#9)
* [Ćwiczenie 230](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np
np.random.seed(20)

np.__version__

'1.22.4'

### <a name='a11'></a> Rozwiązywanie układów równań
Rozważmy układ równań $U$:  
$${\displaystyle \mathrm {U} \colon {\begin{cases}{\begin{matrix}a_{11}x_{1}&+&a_{12}x_{2}&+&\dots &+&a_{1n}x_{n}&=b_{1},\\a_{21}x_{1}&+&a_{22}x_{2}&+&\dots &+&a_{2n}x_{n}&=b_{2},\\\vdots &&\vdots &&\ddots &&\vdots &\vdots \\a_{m1}x_{1}&+&a_{m2}x_{2}&+&\dots &+&a_{mn}x_{n}&=b_{m}.\end{matrix}}\end{cases}}.}$$

Wykorzystując macierze możemy to przedstawić następująco:

$${\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}{\begin{bmatrix}x_{1}\\x_{2}\\\vdots \\x_{n}\end{bmatrix}}={\begin{bmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{bmatrix}}$$
I w zapisie skrótowym:
$$\mathbf {AX} =\mathbf {B}$$

Gdzie:  
$A = {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}$ - macierz współczynników

${\displaystyle \mathbf {B} =[b_{1},b_{2},\dots ,b_{m}]} $ - wektor wyrazów wolnych  
${\mathbf  X}=[x_{1},x_{2},\dots ,x_{n}] $ - wektor niewiadomych

Jeśli macierz układu $A$ jest macierzą kwadratową, to oznaczoność układu jest równoważna jej odwracalności, tzn.
$$\mathbf {AX} =\mathbf {B}$$
$${\displaystyle \mathbf {A} ^{-1}\mathbf {AX} =\mathbf {A} ^{-1}\mathbf {B}} $$
$$\mathbf {X} =\mathbf {A} ^{-1}\mathbf {B} .$$

#### Przykład:
Rozważmy układ równań:
$$\begin{cases}2x + 4y = 10 \\ x - y = -1 \end{cases}$$  
Rozwiązaniem jest para liczb:
$$\begin{cases}x = 1 \\ y = 2 \end{cases}$$  


### <a name='1'></a> Ćwiczenie 221
Wykorzystując bibliotekę numpy rozwiąż poniższy układ równań:

$$\begin{cases}5x - 3y = 21 \\ x - 2y = 7 \end{cases}$$

In [8]:
X = np.array([[5, -3],
              [1, -2]])
Y = np.array([[21],
              [7]])
Z = np.dot(np.linalg.inv(X), Y)
Z

array([[ 3.],
       [-2.]])

Dokonaj sprawdzenia. 

__Wskazówka:__ Użyj funkcji _np.allclose()_.

In [21]:
np.allclose(np.dot(X,Z), Y)

True

### <a name='2'></a> Ćwiczenie 222
Wykorzystując bibliotekę numpy rozwiąż poniższy układ równań:

$$\begin{cases}x + y + z = 1 \\ 2x + y + 5z = 0 \\ x - y = z \end{cases}$$

In [9]:
X = np.array([[1, 1, 1], [2, 1, 5], [1, -1, -1]])
Y = np.array([[1], [0], [0]])
Z = np.dot(np.linalg.inv(X), Y)
Z

array([[ 0.5  ],
       [ 0.875],
       [-0.375]])

Dokonaj sprawdzenia. 

__Wskazówka:__ Użyj funkcji _np.allclose()_.

In [22]:
np.allclose(np.dot(X,Z), Y)

True

### <a name='3'></a> Ćwiczenie 223
Załaduj popularny zbiór danych IRIS do zmiennej _data_raw_ wykorzystując bibliotekę _scikit-learn_.

In [23]:
from sklearn.datasets import load_iris

data_raw = load_iris()
data_raw

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

Wyświetl opis zbioru IRIS

In [24]:
data_raw['DESCR']

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

Wyświetl nazwy zmiennych w zbiorze.

In [27]:
data_raw.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

Wyświetl nazwy klas w zbiorze.

In [28]:
data_raw['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

### <a name='4'></a> Ćwiczenie 224
Do zmiennej _data_ przypisz dane (tablica numpy) zbioru IRIS. 

In [29]:
data = data_raw['data']

Do zmiennej _target_ przypisz wartości zmiennej docelowej ze zbioru IRIS.

In [30]:
target = data_raw['target']

Zbadaj kształt zmiennej _data_ oraz _target_.

In [31]:
print(data.shape)
print(target.shape)

(150, 4)
(150,)


### <a name='5'></a> Ćwiczenie 225
Podziel dane na zbiór treningowy (_data_train_, _target_train_) i testowy (_data_test_, _target_test_). Rozmiar zbioru testowego to 30% próbek.

In [36]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.3)

Wyświetl rozmiar zbiorów:
* _data_train_
* _target_train_
* _data_test_
* _target_test_

In [37]:
print(data_train.shape)
print(target_train.shape)
print(data_test.shape)
print(target_test.shape)

(105, 4)
(105,)
(45, 4)
(45,)


### <a name='6'></a> Ćwiczenie 226 
Zbuduj model regresji logistcznej (ustaw domyślne wartości parametrów) wykorzystując bibliotekę scikit-learn oraz dane IRIS.

In [38]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

Dopasuj dane treningowe do modelu.

In [39]:
model.fit(data_train, target_train)

LogisticRegression()

### <a name='7'></a> Ćwiczenie 227
Dokonaj oceny modelu na zbiorze treningowym.

In [40]:
model.score(data_train, target_train)

0.9904761904761905

Dokonaj oceny modelu na zbiorze testowym.

In [41]:
model.score(data_test, target_test)

0.9555555555555556

### <a name='8'></a> Ćwiczenie 228
Dokonaj predykcji na danych testowych na podstawie modelu i przypisz je do zmiennej _target\_pred_.

In [42]:
target_pred = model.predict(data_test)

Wyświetl zmienną _target\_pred_.

In [43]:
target_pred

array([0, 2, 1, 1, 0, 0, 2, 1, 0, 1, 2, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 1,
       1, 2, 2, 1, 1, 1, 0, 2, 0, 2, 0, 2, 1, 1, 0, 0, 1, 1, 0, 2, 2, 0,
       1])

Wyświetl zmienną _target\_test_.

In [44]:
target_test

array([0, 2, 1, 1, 0, 0, 2, 1, 0, 1, 2, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 1,
       1, 1, 2, 1, 1, 1, 0, 2, 0, 2, 0, 1, 1, 1, 0, 0, 1, 1, 0, 2, 2, 0,
       1])

### <a name='9'></a> Ćwiczenie 229
Wyznacz macierz pomyłek (macierz konfuzji) 

In [46]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(target_test, target_pred)
cm

array([[14,  0,  0],
       [ 0, 17,  2],
       [ 0,  0, 12]])

### <a name='10'></a> Ćwiczenie 230
Wyświetl raport klasyfikacji modelu.

In [47]:
from sklearn.metrics import classification_report
print(classification_report(target_pred, target_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.89      1.00      0.94        17
           2       1.00      0.86      0.92        14

    accuracy                           0.96        45
   macro avg       0.96      0.95      0.96        45
weighted avg       0.96      0.96      0.96        45

