<a href="https://colab.research.google.com/github/LucjanSakowicz/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [4]:
x = np.array([1, 3])
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x.shape

(2,)

In [9]:
x.size

2

In [10]:
x.dtype

dtype('int64')

In [13]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [14]:
x.dtype

dtype('float64')

2D Array

In [19]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [16]:
x.ndim

1

In [20]:
x.shape

(2, 2)

In [21]:
x=np.array([[1,2,4],[4,2,1]])

In [22]:
x.shape

(2, 3)

3D Array

In [25]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     
     [[4,1,1],
      [3,1,2]],
     
     [[4,1,1],
      [3,1,2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 1],
        [3, 1, 2]],

       [[4, 1, 1],
        [3, 1, 2]]])

In [26]:
x.ndim

3

In [27]:
x.shape

(3, 2, 3)

Typy danych

In [28]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [29]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [31]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [33]:
A = np.array([1, 2, 3], dtype='complex') #liczby zlozone
A.dtype

dtype('complex128')

In [35]:
A = np.array([1.1, 2.2, 3.3], dtype='int') #konwersja do int
A
A.dtype

dtype('int64')

In [36]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [38]:
A = np.array([24, 128,230], dtype=np.int8)
A
A.dtype

dtype('int8')

In [39]:
A = np.array([24, 128,230], dtype=np.uint8)
A
A.dtype

dtype('uint8')

Tworzenie tablic

In [40]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [43]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [50]:
np.arange(start=5, stop=100, step=10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [51]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [52]:
np.arange(start=0, stop=1, step=0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [53]:
np.linspace(start=0, stop=1, num=11) #generuje 11 rowno rozlozonych elementów od 0 do 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [57]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
A = A.reshape((3,5))
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
A.reshape((3,-1)) #3 wiersze, python sam dobierze ilosc kolumn, ilosc wszystkich elementow dzielonych przez te wartosc musi zwrocic liczbe calkowita

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
A.reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje na tablicach

In [62]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [63]:
A + B

array([6, 0, 7, 4])

In [64]:
A - B

array([0, 2, 1, 0])

In [65]:
A * B

array([ 9, -1, 12,  4])

In [66]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [67]:
A + 3

array([6, 4, 7, 5])

In [68]:
2 * A

array([6, 2, 8, 4])

In [69]:
A + 3*B

array([12, -2, 13,  8])

In [70]:
np.add(A, B)

array([6, 0, 7, 4])

In [71]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [72]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [73]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [75]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [80]:
np.dot(X, Y) #te trzy operacje sa tozsame, mnozenie macierzy
X.dot(Y)
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie licz pseudolosowych

In [81]:
np.random.seed(0)

In [82]:
np.random.randn() #rozklad normalny

1.764052345967664

In [83]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [84]:
np.random.randn(10, 4) #liczba wierszy, liczba kolumn

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [85]:
np.random.rand() #rozklad jednostajny

0.1965823616800535

In [86]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [87]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [88]:
np.random.randint(10)

3

In [90]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [91]:
np.random.choice([4, 2, 1, 3, 5])

4

In [92]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [94]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.random.shuffle(data)

Podstawowe funkcje w bibliotece numpy

In [96]:
np.exp(1)

2.718281828459045

In [97]:
np.sqrt(9)

3.0

In [98]:
np.all([2, 3, 1])

True

In [99]:
np.any([0, 0, 0])

False

In [100]:
bool(0)

False

In [101]:
bool(1.3)

True

In [102]:
A = np.random.rand(5)
A

array([0.29743695, 0.81379782, 0.39650574, 0.8811032 , 0.58127287])

In [103]:
np.argmax(A)

3

In [104]:
A[np.argmax(A)]

0.8811031971111616

In [105]:
np.argmin(A)

0

In [106]:
np.argsort(A)

array([0, 2, 4, 1, 3])

In [107]:
np.max(A)

0.8811031971111616

In [108]:
np.min(A)

0.29743695085513366

In [109]:
np.mean(A)

0.5940233162303231

In [110]:
np.median(A)

0.5812728726358587

In [111]:
np.std(A)

0.2270924608641256

Indeksowanie, Wycinanie

In [112]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [113]:
# A[idx], A[start:stop], A[:stop], A[start:]
A[2]

2

In [114]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [115]:
A[:2]

array([0, 1])

In [116]:
A[[0, 2]]

array([0, 2])

In [117]:
A[-1]

19

In [118]:
A[10:15]

array([10, 11, 12, 13, 14])

In [119]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [120]:
A[0]

array([0, 1, 2, 3, 4])

In [121]:
A[:, 0]

array([ 0,  5, 10, 15])

In [122]:
A[:, -1]

array([ 4,  9, 14, 19])

In [123]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [124]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [125]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [126]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [127]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [129]:
A.flat #splaszcza tablice do jednego wymiaru

In [128]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru

In [130]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [131]:
A.shape

(4, 5)

In [132]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [133]:
A.ravel() #postac jednowymiarowa

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [134]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [136]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [137]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [138]:
A[A > 0] #zwroci tylko wartosci dodatnie

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [140]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [141]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])